### ISSUE TITLE
Question about Conditional Sampling

### ISSUE THREAD

**Issue by won-bae** [davecasp/add-thin#1]
Hi authors, 

Thank you for sharing the repo for an interesting work! While reading the paper, I was confused with evaluation setting for conditional sampling. In the 2nd paragraph of Sec 5.2, it says `In the experiment, we randomly sample 50 forecasting windows for each sequence from the test set` but what I assumed from the code (https://github.com/davecasp/add-thin/blob/81516667b5f508fed3eb58d8061fe6cadab286ec/add_thin/data.py#L15C1-L15C17) was that `FORECAST_HORIZON` denotes $\Delta T$ (forecasting window) in the paper. 

Is that true? If so, I am not sure about what it meant by `randomly sample 50 forecasting windows`. Could you please elaborate how $\Delta T$ and $T_s$ are determined?

Also, it seems like there is no instruction for training and evaluation yet. Do you have a plan to release it sometime soon? 

Thank you in advance!

**Comment by davecasp** [comment]
The conditional sampling is done as follows:
We uniformly sample 50 forecasting start times, i.e., $T_s\in \[\Delta T, T_{max}-\Delta T\]$. Then $\[0, T_s\]$ is considered the history, while $\[T_s, T_s + \Delta T\]$ is the forecasting window.

We plan on releasing configs as well as training and evaluation instructions within this month. Sorry for the inconvenience.

**Comment by won-bae** [comment]
That makes sense. Thank you for the clarification! Looking forward to playing with the code :)
